### ISSUE TITLE
python setup.py error

### ISSUE THREAD

**Issue by Weipeilang** [davidstutz/mesh-fusion#1]
@davidstutz  when I run this command,it will appear this.What is the problem?
Added OpenMP
running build_ext
cythoning cyfusion.pyx to cyfusion.cpp
building 'cyfusion' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/home/longway/.local/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c cyfusion.cpp -o build/temp.linux-x86_64-2.7/cyfusion.o -ffast-math -msse -msse2 -msse3 -msse4.2 -fopenmp
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/longway/.local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                 from /home/longway/.local/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/longway/.local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from cyfusion.cpp:251:
/home/longway/.local/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/cyfusion.o -L./build/ -lm -lfusion_gpu -o /home/longway/occupancy_networks-master/external/mesh-fusion/libfusiongpu/cyfusion.so -fopenmp

**Comment by davidstutz** [comment]
I can't really spot an error in this output. There are a couple of warnings regarding NumPy. So, this is the output and the code does not work afterwards? What kind of error message do you get when runnign the code? (Or did you cut off some of the errors in the message above, which might come below?)
