### ISSUE TITLE
librenderer.render() (glViewport) throws segfault

### ISSUE THREAD

**Issue by zhusz** [davidstutz/mesh-fusion#11]
Hi David,

Thanks for your nice toolbox! I wish to turn to you for help on one issue of segfault.

I encountered the problem of segfault when calling librenderer.render(). A closer check into the C code indicates that it is the [glViewport](https://github.com/davidstutz/mesh-fusion/blob/master/librender/offscreen.cpp#L131) function that throws the segfault. I tried to run the [test](https://github.com/davidstutz/mesh-fusion/blob/master/librender/test.py) and also encountered the segfault from the same place. I believe I have carefully installed the OpenGL, GLUT and GLEW packages through apt install and it is pretty hard to understand why the glViewport would throw the segfault. I used the headless mode with the xvfb utility. May I know if you have ever encountered the same problem and do you have any clues on this? Many thanks for your time!

**Comment by davidstutz** [comment]
Hi, sorry for not being very responsive.

Never encountered that problem. Also, I did not write ``offscreen.cpp` myself. You could try raising an issue here to get more help: https://github.com/griegler/pyrender
