### ISSUE TITLE
headless rendering doesn't seem to be working

### ISSUE THREAD

**Issue by lodurality** [davidstutz/mesh-fusion#12]
Hi, I was able to run your code on my laptop but headless rendering doesn't seem to be working:

```
freeglut (test): failed to open display ''
```

Code seems to support headless rendering so I am probably missing something simple here.

**Comment by davidstutz** [comment]
Hi, sorry for the delay.

Without any details it is very hard to tell what the problem might be. Also, I am not entirely sure whether I every tried it without any display available. When I was using this code, I was usually running it on a local machine. Reopen if you have more information or found a fix.

**Comment by BJHYZJ** [comment]
I also meet this issue, has anyone found a solution?

**Comment by lodurality** [comment]
@BJHYZJ I ended up running it on local machine.

**Comment by dqj5182** [comment]
I circumvented the problem this script below.
```
xvfb-run -a python 2_fusion.py --mode=render --in_dir=examples/1_scaled/ --depth_dir=examp
les/2_depth/ --out_dir=examples/2_watertight/
```
