### ISSUE TITLE
CUDA error in fusion step

### ISSUE THREAD

**Issue by Hippogriff** [davidstutz/mesh-fusion#13]
I am getting the following warning in fusion step, which makes the code to not use GPU:
````
no kernel image is available for execution on the device in libfusiongpu/fusion.cu at 51
````

I am using Titan V gpu with cuda 11.2.

**Comment by bharat-b7** [comment]
Facing the same issue, did anyone find a fix?

Update: I managed to get it working by selecting correct gencode for my GPU in the following lines in `libfusiongpu/CMakeLists.txt`:
```
set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS}; -gencode=arch=compute_30,code=sm_30")
set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS}; -gencode=arch=compute_30,code=compute_30")
```

**Comment by davidstutz** [comment]
Thanks @bharat-b7 for sharing the fix, will mention it in the README.
