### ISSUE TITLE
Figure out the rotation applied by marching cubes

### ISSUE THREAD

**Issue by jingnanshi** [davidstutz/mesh-fusion#14]
I am wondering whether it's possible to revert the rotation applied by the marching cubes algorithm after obtaining the watertight meshes. The scaling and translation components can easily be retrieved, however I'm not sure to figure out how to log the rotations applied in the marching cubes step. Thanks!

**Comment by davidstutz** [comment]
I am actually not quite sure which rotation you are exactly referring to. Can you give some more details?

**Comment by jingnanshi** [comment]
Hi @davidstutz, thank you for your response. Sorry for being unclear --- I was referring to the change of coordinate frames when the marching cubes algorithm is applied.

**Comment by davidstutz** [comment]
Sorry, I am not sure whether this is possible.
