### ISSUE TITLE
can't work on headless cluster

### ISSUE THREAD

**Issue by ray8828** [davidstutz/mesh-fusion#16]
Hi, thanks for sharing this great project, which would be quite useful when generating new datasets. However, it can't work on our cluster for now, I'm using libfusion_cpu, and i always get 

freeglut (test): failed to open display

error, could you help to fix the issue? Thanks!

**Comment by davidstutz** [comment]
I remember this issue but I cannot exactly remember how to fix it. Essentially, you need to make sure that you have access to a display for rendering (not necessarily a physical one) and some cluster servers might not provide this.
