### ISSUE TITLE
Error: GL/glew.h: No such file or directory

### ISSUE THREAD

**Issue by UncleTom111** [davidstutz/mesh-fusion#18]
Hi David,

Thanks for your nice tools. 
When building pyrender, I encountered the problem below.
Should I install OpenGL, GLEW and GLUT first? And could you please tell me how to install these pakcages or libraries properly?

================================================
In file included from pyrender.cpp:770:0:
offscreen.h:4:10: fatal error: GL/glew.h: No such file or directory
 #include "GL/glew.h"
          ^~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
================================================

**Comment by UncleTom111** [comment]
```sudo apt install freeglut3-dev mesa-utils```
```sudo apt-get install libglew-dev```

**Comment by Libuyan00** [comment]
> `sudo apt install freeglut3-dev mesa-utils` `sudo apt-get install libglew-dev`

![image](https://github.com/davidstutz/mesh-fusion/assets/82650092/f7f2f51f-4cd0-444b-8c8f-901f284d71c0)
I tried this method and encountered the following errors. I tried to find the answers on the Internet myself, but it didn't work out. Can you help me? Thank you

**Comment by dqj5182** [comment]
@UncleTom111 Thanks! This worked for me

**Comment by LaFeuilleMorte** [comment]
> > `sudo apt install freeglut3-dev mesa-utils` `sudo apt-get install libglew-dev`
> 
> ![image](https://private-user-images.githubusercontent.com/82650092/247138963-f7f2f51f-4cd0-444b-8c8f-901f284d71c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjIyNTQsIm5iZiI6MTcyMDQyMTk1NCwicGF0aCI6Ii84MjY1MDA5Mi8yNDcxMzg5NjMtZjdmMmY1MWYtNGNkMC00NDRiLThjOGYtOTAxZjI4NGQ3MWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA2NTkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkOTNlNGYzMTJiNzZmOGQ2MDg4MzQwNzdiYTFmY2UxMWEzMjVjMWE5ZmQxZjQ4OTI5OWI5MWQ3YjNiMjRlYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TJCCkchP5q09_f9uQqYCGHHpDSHd_xxT0D9nzBQ8XLI) I tried this method and encountered the following errors. I tried to find the answers on the Internet myself, but it didn't work out. Can you help me? Thank you

you can try to update the source.list
