### ISSUE TITLE
Post-processing

### ISSUE THREAD

**Issue by nicolasugrinovic** [davidstutz/mesh-fusion#2]
Thanks so much for sharing this library. 
I was wondering, do you use any type of post-processing like smoothing to get such a good mesh outputs? Or is it the intersection technique in Marching Cubes algorithm, meaning the way you cut the edges?
Thank you

**Comment by davidstutz** [comment]
Sorry for the late reply!

There is no special post-processing; the images in the README are the result of running the fusion part. After simplifications, some of the smoothness might be lost, though. The main factor for getting very smooth shapes is having many high-resolution depth images -- this means playing around with `n_views`, `image_height`, `image_width` and the other parameters of `2_fusion.py`. However, the result will also contain more faces which makes post-processing and simplification more difficult and time-consuming.

Hope that answers your question.
