### ISSUE TITLE
python setup.py build_ext --inplace  error

### ISSUE THREAD

**Issue by ivyone** [davidstutz/mesh-fusion#3]
Hi,I'm new to mesh-fashion.An error occurred when I run this command.

running build_ext
skipping 'cyfusion.cpp' Cython extension (up-to-date)
building 'cyfusion' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I//anaconda3/include -arch x86_64 -I//anaconda3/include -arch x86_64 -I//anaconda3/lib/python3.7/site-packages/numpy/core/include -I//anaconda3/include/python3.7m -c cyfusion.cpp -o build/temp.macosx-10.7-x86_64-3.7/cyfusion.o -ffast-math -msse -msse2 -msse3 -msse4.2
warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on
      the command line to use the libc++ standard library instead
      [-Wstdlibcxx-not-found]
In file included from cyfusion.cpp:612:
In file included from //anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from //anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
In file included from //anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1824:
//anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: 
      "Using deprecated NumPy API, disable it with "          "#define
      NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \
 ^
**cyfusion.cpp:615:10: fatal error: 'cstdio' file not found
#include <cstdio>
         ^~~~~~~~**
**2 warnings and 1 error generated.
error: command 'gcc' failed with exit status 1**

**Comment by davidstutz** [comment]
Seems like your compiler cannot find cstdio (see http://www.cplusplus.com/reference/cstdio/). Did you check whether a simple Hello World C program can find cstdio? If not, there might be some issue with your compiler. Note that cstdio is used in these files: https://github.com/davidstutz/mesh-fusion/search?q=cstdio&unscoped_q=cstdio. So that's a good place to start debugging.

**Comment by ivyone** [comment]
Thanks for replying me.Actually it was caused by macOS version issue.I have solved it.
