### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by Dustinpro** [davidstutz/mesh-fusion#4]
Related libraries have been installed. But it does not seem to work out. @davidstutz 

libfusiongpu$ python setup.py build_ext --inplace
Added OpenMP
running build_ext
skipping 'cyfusion.cpp' Cython extension (up-to-date)
building 'cyfusion' extension
creating build/temp.linux-x86_64-3.7

...

cyfusion.cpp: In function ‘void __Pyx__ExceptionSave(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
cyfusion.cpp:24028:21: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     *type = tstate->exc_type;
                     ^
cyfusion.cpp:24029:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     *value = tstate->exc_value;
                      ^
cyfusion.cpp:24030:19: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     *tb = tstate->exc_traceback;
                   ^
cyfusion.cpp: In function ‘void __Pyx__ExceptionReset(PyThreadState*, PyObject*, PyObject*, PyObject*)’:
cyfusion.cpp:24037:24: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     tmp_type = tstate->exc_type;
                        ^
cyfusion.cpp:24038:25: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     tmp_value = tstate->exc_value;
                         ^
cyfusion.cpp:24039:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     tmp_tb = tstate->exc_traceback;
                      ^
cyfusion.cpp:24040:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     tstate->exc_type = type;
             ^
cyfusion.cpp:24041:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     tstate->exc_value = value;
             ^
cyfusion.cpp:24042:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     tstate->exc_traceback = tb;
             ^
cyfusion.cpp: In function ‘int __Pyx__GetException(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
cyfusion.cpp:24112:24: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     tmp_type = tstate->exc_type;
                        ^
cyfusion.cpp:24113:25: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     tmp_value = tstate->exc_value;
                         ^
cyfusion.cpp:24114:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     tmp_tb = tstate->exc_traceback;
                      ^
cyfusion.cpp:24115:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     tstate->exc_type = local_type;
             ^
cyfusion.cpp:24116:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     tstate->exc_value = local_value;
             ^
cyfusion.cpp:24117:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     tstate->exc_traceback = local_tb;
             ^
cyfusion.cpp: In function ‘void __Pyx__ExceptionSwap(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
cyfusion.cpp:24354:24: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     tmp_type = tstate->exc_type;
                        ^
cyfusion.cpp:24355:25: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     tmp_value = tstate->exc_value;
                         ^
cyfusion.cpp:24356:22: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     tmp_tb = tstate->exc_traceback;
                      ^
cyfusion.cpp:24357:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_type’
     tstate->exc_type = *type;
             ^
cyfusion.cpp:24358:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_value’
     tstate->exc_value = *value;
             ^
cyfusion.cpp:24359:13: error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’
     tstate->exc_traceback = *tb;
             ^
error: command 'gcc' failed with exit status 1

**Comment by Wishmitha** [comment]
What's the solution for this?

**Comment by davidstutz** [comment]
For me it seems like a Cython error, maybe an incompatibility between Cython and Python. Hard to tell without the exact versions though.

**Comment by Dustinpro** [comment]
I used the latest Cython version and Python 3.7.4. I changed all "exc_*" to "curexc_*," and it worked.

**Comment by anilesec** [comment]
> I used the latest Cython version and Python 3.7.4. I changed all "exc__" to "curexc__," and it worked.

Hey, It worked for me too. Thanks! How did you figure out that?

**Comment by Dustinpro** [comment]
> > I used the latest Cython version and Python 3.7.4. I changed all "exc__" to "curexc__," and it worked.
> 
> Hey, It worked for me too. Thanks! How did you figure out that?

I remembered that I searched for various combinations of keywords on the StackOverflow. There was a similar question that made that change to handle another related error. Then, I checked the Cython doc and got the point.

**Comment by anilesec** [comment]
THanks for response :)
Build is successful for me but when I try to run second step using 
python 2_fusion.py --mode=fuse --in_dir=examples/1_scaled/ --depth_dir=examples/2_depth/ --
out_dir=examples/2_watertight/

I get the following error:
Traceback (most recent call last):
  File "2_fusion.py", line 10, in <module>
    import librender
  File "/home/aswamy/projects/mesh-fusion/librender/__init__.py", line 5, in <module>
    ctypes.cdll.LoadLibrary(os.path.join(pyrender_dir, 'pyrender.so'))
  File "/home/aswamy/tools/anaconda3/envs/mesh-fusion/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/home/aswamy/tools/anaconda3/envs/mesh-fusion/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
**OSError: /home/aswamy/projects/mesh-fusion/librender/pyrender.so: cannot open shared object file: No such file or directory**

Do you have any idea why this error despite successful build?

Thank you!

**Comment by aidendef** [comment]
@anilesec  Hi anilesec

Did you solve this problem?

**OSError: /home/aswamy/projects/mesh-fusion/librender/pyrender.so: cannot open shared object file: No such file or directory**

**Comment by msingh27** [comment]
Using force flag while installing the setup solved my problem: 
`python setup.py build_ext -i -f
`
reference : [https://stackoverflow.com/questions/65695724/error-pythreadstate-aka-struct-ts-has-no-member-named-exc-type-did-yo](url)
