### ISSUE TITLE
Save individual pose for each depth view

### ISSUE THREAD

**Issue by rjtshrm** [davidstutz/mesh-fusion#5]
Is it possible to save each view separately such that its depth map, intrinsic and pose information is saved on the disk. I do not want to use the fusion pipeline together with the rendering part. However, I tried to read the code and save intrinsic, R, T values. But when I fused those data the results are nonsense. Can you update me on this?

**Comment by davidstutz** [comment]
Not sure if I can follow you (I am also not that up-to-date anymore on this code base). You can easily save the individual depth maps in de render function in 2_fusion.py as images (I used that for debugging). The intrinsics are fixed when I remember correctly (see __init__ in 2_fusion.py). With pose estimation you probably mean the extrinsics (camera location). I do not remember the exact format of R and T used throughout the code (I remember that people use slightly different formats here, which makes it seem like nonsense sometimes). You can have a look at libfusioncpu/fusion.h (specifically lines 101ff) to see how R and T is used, I hope that is enough to deduce and make sense of R and T.
